"""Infrastructure-as-code fix generator for detected issues."""
from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from backend.models import FixPlan, Issue
from backend.utils.logging_utils import get_logger

LOGGER = get_logger(__name__)


class FixGenerator:
    """Generate Terraform/Python fixes and persist versions locally."""

    def __init__(self, output_dir: str = "iac_versions"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, issues: list[Issue]) -> FixPlan:
        """Generate a consolidated fix plan for the provided issues.

        The resulting plan is written to ``self.output_dir`` with a timestamped filename
        so the remediation pipeline can be replayed for auditability.
        """

        tool = "terraform"
        content_lines: list[str] = [
            "# Autogenerated remediation plan",
            "terraform {",
            "  required_version = \">= 1.0.0\"",
            "}",
            "",
        ]

        for issue in issues:
            content_lines.extend(self._render_issue_fix(issue))
            content_lines.append("")

        content = "\n".join(content_lines)
        timestamp = datetime.now(UTC).strftime("%Y%m%d%H%M%S")
        output_path = self.output_dir / f"fix_{timestamp}.tf"

        try:
            output_path.write_text(content, encoding="utf-8")
            LOGGER.info("Persisted IaC fix to %s", output_path)
        except OSError as exc:  # pragma: no cover - defensive
            LOGGER.error("Unable to persist IaC fix: %s", exc)
            raise

        return FixPlan(
            tool=tool,
            content=content,
            validation_passed=True,
            output_path=str(output_path),
        )

    def _render_issue_fix(self, issue: Issue) -> list[str]:
        """Return Terraform snippets for an issue.

        The snippets are intentionally minimal yet idempotent to demonstrate a
        deterministic remediation workflow inside the simulator.
        """

        resource_meta = issue.resource
        if issue.issue_type == "Publicly exposed storage":
            bucket_name = resource_meta.get("name", "bucket")
            return [
                f"resource \"aws_s3_bucket_public_access_block\" \"{bucket_name}\" {{",
                f"  bucket = \"{bucket_name}\"",
                "  block_public_acls   = true",
                "  block_public_policy = true",
                "  ignore_public_acls  = true",
                "  restrict_public_buckets = true",
                "}",
            ]
        if issue.issue_type == "Unencrypted storage":
            name = resource_meta.get("name", "storage")
            return [
                f"resource \"aws_s3_bucket_server_side_encryption_configuration\" \"{name}\" {{",
                "  rule {",
                "    apply_server_side_encryption_by_default {",
                "      sse_algorithm = \"aws:kms\"",
                "    }",
                "  }",
                "}",
            ]
        if issue.issue_type == "Exposed network ports":
            sg_name = resource_meta.get("name", "sg")
            return [
                f"resource \"aws_security_group_rule\" \"{sg_name}_restricted\" {{",
                "  type              = \"ingress\"",
                "  cidr_blocks       = [\"10.0.0.0/16\"]",
                "  from_port         = 443",
                "  to_port           = 443",
                "  protocol          = \"tcp\"",
                f"  security_group_id = aws_security_group.{sg_name}.id",
                "}",
            ]
        if issue.issue_type == "IAM privilege escalation risk":
            role_name = resource_meta.get("name", "role")
            return [
                f"data \"aws_iam_policy_document\" \"{role_name}_least_privilege\" {{",
                "  statement {",
                "    actions   = [\"s3:ListBucket\"]",
                "    resources = [\"*\"]",
                "  }",
                "}",
                f"resource \"aws_iam_role_policy\" \"{role_name}_policy\" {{",
                f"  role   = aws_iam_role.{role_name}.id",
                f"  policy = data.aws_iam_policy_document.{role_name}_least_privilege.json",
                "}",
            ]
        if issue.issue_type == "Missing MFA":
            return [
                "resource \"aws_iam_account_password_policy\" \"strict\" {",
                "  require_numbers   = true",
                "  require_uppercase = true",
                "  require_lowercase = true",
                "  require_symbols   = true",
                "  minimum_password_length = 14",
                "  allow_users_to_change_password = true",
                "  hard_expiry = true",
                "  max_password_age = 90",
                "  password_reuse_prevention = 24",
                "}",
            ]
        if issue.issue_type == "Misconfigured KMS keys":
            key_alias = resource_meta.get("name", "kms_key")
            return [
                f"resource \"aws_kms_key\" \"{key_alias}\" {{",
                "  enable_key_rotation = true",
                "}",
                f"resource \"aws_kms_alias\" \"{key_alias}_alias\" {{",
                f"  name          = \"alias/{key_alias}\"",
                f"  target_key_id = aws_kms_key.{key_alias}.key_id",
                "}",
            ]
        if issue.issue_type == "Vulnerable runtime":
            fn_name = resource_meta.get("name", "lambda")
            return [
                f"resource \"aws_lambda_function\" \"{fn_name}\" {{",
                "  runtime = \"python3.11\"",
                "  handler = \"index.handler\"",
                "  filename = \"function.zip\"",
                "}",
            ]
        return ["# No-op for unrecognized issue types"]
